- assets/styles/overrides/_headings.scss
- lib/ACF/ArtistGroup.php
- lib/PostType/Artist.php
- models/single-artist.php
- partials/shared/additional-info-list.dust
- partials/shared/additional-info-row.dust
- partials/single-artist.dust
Adds artist CPT & single view
TMS-145
> TMS-145: Artist

- CHANGELOG.MD
- lib/Localization.php
- lib/ThemeController.php
Make artists & artist categories translatable by default
> Feature: Localize artists

- CHANGELOG.MD
- assets/styles/overrides/_primary-nav.scss
- assets/styles/overrides/index.scss
Change primary navigation typography in order to follow layout.
> Fix: primary navigation typography

- CHANGELOG.MD
- lib/ACF/AlterSettingsGroup.php
- lib/ACF/ArtistGroup.php
- lib/ACF/Fields/Settings/ArtistSettingsTab.php
- partials/shared/additional-info-list.dust
- partials/shared/additional-info-row.dust
- partials/single-artist.dust
> TMS-216: Pre fill artist additional information from settings

- CHANGELOG.MD
- lib/ThemeCustomizationController.php
Setup search results colors
TMS-213
TMS-10
> TMS-213: Search results

- CHANGELOG.MD
- assets/fonts/fonts.js
Changed typekit ID to client provided.
TMS-227 (CR: TMS-10)
> TMS-227: Typekit id

- CHANGELOG.MD
- lib/ACF/ArtistGroup.php
- package-lock.json
- partials/single-artist.dust
[https://geniemdev.atlassian.net/browse/TMS-10](https://geniemdev.atlassian.net/browse/TMS-10)
Changes to single artist's layout. Added field for short description.
Client apparently wanted short description in addition to description field. Therefore, the elements' order on the page had to be changed as well. 
[https://geniemdev.atlassian.net/browse/TMS-357](https://geniemdev.atlassian.net/browse/TMS-357)
Tested visually and by comparing Figma to staging sites
Tested with `composer lint-all `
> TMS 357 Taitelija-sivun muutokset

- CHANGELOG.MD
- partials/shared/additional-info-row.dust
[https://geniemdev.atlassian.net/browse/TMS-10](https://geniemdev.atlassian.net/browse/TMS-10)
- Font fix for single artist's page's table element. 
- Changelog fixed.
The text styles were different than in Figma.
[https://geniemdev.atlassian.net/browse/TMS-358](https://geniemdev.atlassian.net/browse/TMS-358)
Tested visually and by comparing Figma to staging sites
Tested with composer lint-all
> TMS 358-2 Taulukossa on liian pieni ja väärä fontti

- CHANGELOG.MD
- assets/styles/overrides/_footer.scss
CR: https://geniemdev.atlassian.net/browse/TMS-10
Tampere logo focus styles
TMS-413
> TMS-413: Tampere logo focus styles

- CHANGELOG.MD
- partials/shared/additional-info-list.dust
- partials/shared/additional-info-row.dust
CR: https://geniemdev.atlassian.net/browse/TMS-10
Template conditions that title and text exists for artist's additional info row.
[https://geniemdev.atlassian.net/browse/TMS-370](https://geniemdev.atlassian.net/browse/TMS-370)
Locally by empty values.
> TMS-370: Hide Artist's additional info row if title or text empty

- assets/styles/layouts/_articles.scss
- assets/styles/layouts/_content-columns.scss
- assets/styles/layouts/_events.scss
- assets/styles/layouts/_logo-wall.scss
- assets/styles/layouts/index.scss
- assets/styles/overrides/_headings.scss
- assets/styles/ui-components/_pill.scss
- assets/styles/ui-components/index.scss
- assets/styles/views/_single.scss
- assets/styles/views/index.scss
- lib/Formatters/HeroFormatter.php
> TMS-421-layouts

- CHANGELOG.MD
- partials/blocks/block-image-gallery.dust
CR: https://geniemdev.atlassian.net/browse/TMS-10
Overriding template for image gallery.
TMS-421
Locally
> TMS-421-2: Fix is_clickable setting handling in img gallery block's partial 

- CHANGELOG.MD
- assets/styles/blocks/_image-gallery.scss
- assets/styles/blocks/_index.scss
- assets/styles/main.scss
- assets/styles/overrides/_notice-banner.scss
- lib/ThemeCustomizationController.php
> TMS-421: Misc style fixes

- CHANGELOG.MD
- assets/styles/overrides/_events.scss
- assets/styles/overrides/index.scss
CR: https://geniemdev.atlassian.net/browse/TMS-10
Hide event categories
TMS-560
> TMS-560: Hide event categories

- CHANGELOG.MD
- lib/ThemeCustomizationController.php
Use formatter filters for modifying image carousel
TMS-421
> TMS-421: Use formatter filters for modifying image carousel

- CHANGELOG.MD
- assets/styles/overrides/_notice-banner.scss
Update notice banner colors
TMS-421
> TMS-421: Update notice banner colors

- CHANGELOG.MD
- assets/styles/views/_archive-artist.scss
- lib/ACF/ArtistCategoryGroup.php
- models/archive-artist.php
- models/page-orchester.php
- partials/archive-artist.dust
- partials/page-orchester.dust
- partials/ui/artist-item.dust
Add page template orchester
TMS-911
> TMS-911: Add page template orchester

- CHANGELOG.MD
- lib/ACF/ArtistGroup.php
- models/archive-artist.php
- partials/archive-artist.dust
Group artist archive results by category
TMS-911
> TMS-911-2: Group artist archive results by category

- CHANGELOG.MD
- assets/styles/layouts/_hero.scss
- lib/ACF/Layouts/HeroLayout.php
- partials/layouts/layout-hero.dust
- style.css
Task: https://geniemdev.atlassian.net/browse/TMS-922
> TMS-922: Add link possibility to filharmonia hero description

- lib/ThemeSupports.php
Task: https://geniemdev.atlassian.net/browse/PIEN-8359
> PIEN-8359: Allow custom url links in menus

- CHANGELOG.MD
- partials/ui/menu/menu-item-dropdown-content.dust
- partials/ui/menu/menu-item-single.dust
- partials/ui/menu/menu-item.dust
- style.css
Task: https://geniemdev.atlassian.net/browse/TMS-931
Accessibility fixes to navigation
> TMS-931: Navigation accessibility fixes

- CHANGELOG.MD
- assets/styles/overrides/_footer.scss
- style.css
Severa-ID: 2108
Severa-kuvaus: TMS-1028 Uusi elementti: somelinkkilista
Task: https://hiondigital.atlassian.net/browse/TMS-1028
Fix footer social-media icon color
> TMS-1028: Fix footer social-media icon color

- CHANGELOG.MD
- assets/styles/views/_single.scss
Severa-ID: 2129
Severa-kuvaus: TMS-1058 Artikkelin pääotsikon tyylin muutos
Task: https://hiondigital.atlassian.net/browse/TMS-1058
Remove text-decoration & decrease font-size for single-post h1-heading
> TMS-1058: Remove text-decoration & decrease font-size for post heading

- CHANGELOG.MD
- partials/ui/event-highlight.dust
Severa-ID: 2108
Severa-kuvaus: TMS-1100 Tapahtumaan useampi paikka näkyviin
Task: https://hiondigital.atlassian.net/browse/TMS-1100
- Show multiple locations for events if available
- Add "and other locations" text in event-highlights if multiple locations exist
> TMS-1100: Show multiple locations for events if available

- CHANGELOG.MD
- assets/styles/layouts/_hero.scss
Severa-ID: 2129
Severa-kuvaus: TMS-1137 Museo-heron otsikon värimuutos
Task: https://hiondigital.atlassian.net/browse/TMS-1137
Change hero-museum heading color
> TMS-1137: Change hero-museum heading color

- CHANGELOG.MD
- partials/ui/menu/language-nav.dust
- partials/ui/menu/menuitem-secondary.dust
Severa-ID: 2129
Severa-kuvaus: TMS-1142 Tukivalikkoon ja kielenvaihtajaan fonttimuutos
Task: https://hiondigital.atlassian.net/browse/TMS-1142
Change top-menu fonts, add partial to remove secondary-font-family class
> TMS-1142: Change top-menu fonts

- CHANGELOG.MD
- assets/styles/views/_single-dynamic-event.scss
Severa-ID: 2247
Severa-kuvaus: TMS-1153 Tapahtumakalenterin tapahtuma, rivivälit
Task: https://hiondigital.atlassian.net/browse/TMS-1153
Decrease event-page paragraph margins
> TMS-1153: Decrease event-page content margins

- CHANGELOG.MD
- assets/styles/overrides/_header-top.scss
- assets/styles/overrides/_primary-nav.scss
Severa-ID: 2247
Severa-kuvaus: TMS-1160 Saavutettavuus: Vapriikin kohdistuksia puuttuu + muutoksia niihin
Task: https://hiondigital.atlassian.net/browse/TMS-1160
Improve focus outlines for elements to improve accessibility
> TMS-1160: Fix elements focus outline thickness
